# Generated by Django 3.2.7 on 2021-09-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='Class',
        ),
        migrations.AlterModelTable(
            name='class',
            table='Class',
        ),
    ]
